// Generated by CoffeeScript 1.6.2
(function() {
  define('controllers/pagesController', ['views/pages/main', 'views/pages/about'], function(main, about) {
    var Controller;

    Controller = (function() {
      function Controller() {
        this.main = main;
        this.about = about;
      }

      return Controller;

    })();
    return new Controller;
  });

}).call(this);
