// Generated by CoffeeScript 1.6.2
(function() {
  var Users, app, express, http, io, mongo, port, schema;

  express = require('express');

  http = require('http');

  port = 3000;

  app = express();

  mongo = require('mongoose');

  app.set('port', process.env.PORT || port);

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.set('views', __dirname + '/views');

  app.set('view engine', "jade");

  app.engine('jade', require('jade').__express);

  app.use(express["static"](__dirname + '/public'));

  schema = new mongo.Schema({
    name: String,
    email: String,
    age: Number
  });

  Users = mongo.model('Users', schema);

  mongo.connect('mongodb://localhost/helloExpress');

  app.get('/', function(req, res) {
    return res.send('it works!');
  });

  app.get('/api/', function(req, res) {});

  io = require('socket.io').listen(app.listen(port));

  io.sockets.on("connection", function(socket) {
    console.log('connected');
    return socket.on("posts:read", function(data) {
      console.log('read');
      return console.log(data);
    });
  });

}).call(this);
